services:
  osrm:
    image: osrm/osrm-backend:latest
    container_name: sisped-osrm
    volumes:
      - sisped_osrmdata:/data
    ports:
      - "5000:5000"
    command: ["osrm-routed", "--port", "5000", "/data/region.osrm"]
    restart: unless-stopped

volumes:
  sisped_osrmdata:
    name: sisped_osrmdata
